---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: contactfrontendappdeployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: contactfrontend
 template:
  metadata:
   name: contactfrontend
   labels:
     app: contactfrontend
  spec:
    containers:
    - name: contactfrontendcontainer
      image: zapdocker2022/contact_ui_ng_app
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: contactfrontendsvc
spec:
  type: NodePort
  selector:
   app: contactfrontend
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30005
...
